tableG029 = {
    '01': 'Crédito em Conta Corrente',
    '02': 'Cheque Pagamento / Administrativo',
    '03': 'DOC/TED (1) (2)',
    '04': 'Cartão Salário (somente para tipo de Serviço = ''30'')',
    '05': 'Crédito em Conta Poupança',
    '06': 'Liberação de Títulos HSBC',
    '07': 'Emissão de Cheque Salário',
    '08': 'Liquidação de Parcelas de Cobrança não Registrada',
    '09': 'Arrecadação de Tributos Federais',
    '10': 'OP à Disposição',
    '11': 'Pagamento de Contas e Tributos com Código de Barras',
    '12': 'Doc Mesma Titularidade',
    '13': 'Pagamentos de Guias',
    '14': 'Credito em Conta Corrente Mesma Titularidade',
    '16': 'Tributo - DARF Normal',
    '17': 'Tributo - GPS (Guia da Previdência Social)',
    '18': 'Tributo - DARF Simples',
    '19': 'Tributo - IPTU - Prefeituras',
    '20': 'Pagamento com Autenticação',
    '21': 'Tributo - DARJ',
}